"""
generator.py
~~~~~~~~~~~~
Export analysis results to structured Markdown and JSON reports.
"""

from __future__ import annotations

import json
import textwrap
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def _now() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def to_json(sessions: pd.DataFrame, commands: pd.DataFrame, out_path: str | Path) -> Path:
    """Write a machine-readable JSON report."""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": _now(),
        "sessions": json.loads(sessions.to_json(orient="records", date_format="iso")),
        "commands": json.loads(commands.to_json(orient="records", date_format="iso")),
    }
    out = Path(out_path)
    out.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    return out


def to_markdown(
    sessions: pd.DataFrame,
    commands: pd.DataFrame,
    geo: dict,
    out_path: str | Path,
    source: str = "cowrie.json",
) -> Path:
    """Write a human-readable Markdown incident report."""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# 🛡 Honeypot-AI — Threat Intelligence Report",
        "",
        f"**Generated:** {_now()}  ",
        f"**Source:** `{source}`",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    total_sessions = len(sessions)
    unique_ips = sessions["src_ip"].nunique() if "src_ip" in sessions.columns else 0
    critical = (sessions["threat_level"] == "CRITICAL").sum() if "threat_level" in sessions.columns else 0
    high = (sessions["threat_level"] == "HIGH").sum() if "threat_level" in sessions.columns else 0

    lines += [
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Sessions | **{total_sessions}** |",
        f"| Unique Attacker IPs | **{unique_ips}** |",
        f"| CRITICAL Threat Sessions | **{critical}** |",
        f"| HIGH Threat Sessions | **{high}** |",
        f"| Total Commands Captured | **{len(commands)}** |",
        "",
        "---",
        "",
        "## Top Threat Sessions",
        "",
    ]

    if not sessions.empty and "threat_score" in sessions.columns:
        top = sessions.nlargest(10, "threat_score")[
            [c for c in ["session", "src_ip", "threat_score", "threat_level", "cmd_count"] if c in sessions.columns]
        ]
        lines.append(top.to_markdown(index=False))
    else:
        lines.append("_No session data._")

    lines += [
        "",
        "---",
        "",
        "## Top Commands",
        "",
    ]

    if not commands.empty:
        top_cmds = (
            commands.groupby(["input", "intent"])
            .size()
            .reset_index(name="count")
            .nlargest(20, "count")
        )
        lines.append(top_cmds.to_markdown(index=False))
    else:
        lines.append("_No command data._")

    lines += [
        "",
        "---",
        "",
        "## Attacker Geolocation",
        "",
    ]

    if geo:
        geo_rows = [
            {"IP": ip, "Country": v.get("country", "?"), "City": v.get("city", "?"), "ISP": v.get("isp", "?")}
            for ip, v in geo.items()
        ]
        geo_df = pd.DataFrame(geo_rows)
        lines.append(geo_df.to_markdown(index=False))
    else:
        lines.append("_No GeoIP data._")

    lines += ["", "---", "", "_Report generated by [honeypot-ai](https://github.com/mihirdixit/honeypot-ai)_", ""]

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
